//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicUploadWpfApplication.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormFillUpResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormFillUpResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicUploadWpfApplication.App_GlobalResources.FormFillUpResource", typeof(FormFillUpResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Telephone No..
        /// </summary>
        internal static string AltTelNo {
            get {
                return ResourceManager.GetString("AltTelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group.
        /// </summary>
        internal static string BloodGroup {
            get {
                return ResourceManager.GetString("BloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course applied for.
        /// </summary>
        internal static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired User Name.
        /// </summary>
        internal static string DesiredUserName {
            get {
                return ResourceManager.GetString("DesiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        internal static string EmailId {
            get {
                return ResourceManager.GetString("EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        internal static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th.
        /// </summary>
        internal static string FifthYear {
            get {
                return ResourceManager.GetString("FifthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st.
        /// </summary>
        internal static string FirstYear {
            get {
                return ResourceManager.GetString("FirstYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th.
        /// </summary>
        internal static string FourthYear {
            get {
                return ResourceManager.GetString("FourthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father/Husband Name.
        /// </summary>
        internal static string GaurdianName {
            get {
                return ResourceManager.GetString("GaurdianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string GroupA {
            get {
                return ResourceManager.GetString("GroupA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB.
        /// </summary>
        internal static string GroupAB {
            get {
                return ResourceManager.GetString("GroupAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string GroupB {
            get {
                return ResourceManager.GetString("GroupB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string GroupO {
            get {
                return ResourceManager.GetString("GroupO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husband.
        /// </summary>
        internal static string Husband {
            get {
                return ResourceManager.GetString("Husband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No..
        /// </summary>
        internal static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -ve.
        /// </summary>
        internal static string Negetive {
            get {
                return ResourceManager.GetString("Negetive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User??.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkey.
        /// </summary>
        internal static string Passkey {
            get {
                return ResourceManager.GetString("Passkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.G Final.
        /// </summary>
        internal static string PGFinal {
            get {
                return ResourceManager.GetString("PGFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.G Previous.
        /// </summary>
        internal static string PGPrev {
            get {
                return ResourceManager.GetString("PGPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +ive.
        /// </summary>
        internal static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Me.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Here.
        /// </summary>
        internal static string RegisterHere {
            get {
                return ResourceManager.GetString("RegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar No..
        /// </summary>
        internal static string ScholarNo {
            get {
                return ResourceManager.GetString("ScholarNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd.
        /// </summary>
        internal static string SecondYear {
            get {
                return ResourceManager.GetString("SecondYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone No (with STD-Code).
        /// </summary>
        internal static string TelNo {
            get {
                return ResourceManager.GetString("TelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd.
        /// </summary>
        internal static string ThirdYear {
            get {
                return ResourceManager.GetString("ThirdYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        internal static string TitleMiss {
            get {
                return ResourceManager.GetString("TitleMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        internal static string TitleMr {
            get {
                return ResourceManager.GetString("TitleMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs..
        /// </summary>
        internal static string TitleMrs {
            get {
                return ResourceManager.GetString("TitleMrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Details.
        /// </summary>
        internal static string UpdateDetails {
            get {
                return ResourceManager.GetString("UpdateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
